### ISSUE TITLE
Confirm that exporter works with coins

### ISSUE THREAD

**Issue by fanatid** [ExodusMovement/bitcoind-exporter#3]
Coins:
```
bitcoin
bitcoincash
bitcoingold
dash
digibyte
dogecoin
litecoin
qtum
vertcoin
zcash
```

**Comment by roccomuso** [comment]
Tested with:

- [x] bitcoin
- [x] bitcoincash
- [x] bitcoingold
- [x] dash
- [x] digibyte
- [x] dogecoin
- [x] litecoin
- [x] qtum
- [x] vertcoin
- [x] zcash

**Comment by fanatid** [comment]
Please also change string to choice here: https://github.com/ExodusMovement/bitcoind-exporter/blob/0a39638926155de7e408eee5b6f55967c234a4c2/index.js#L37
All these coins should be listed there.
